# SPDX-License-Identifier: GPL-2.0-or-later
include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI eBPF/XDP Offload Telemetry Dashboard
LUCI_DEPENDS:=+luci-base
LUCI_PKGARCH:=all

PKG_LICENSE:=GPL-2.0-or-later
PKG_MAINTAINER:=Joel Wiramu Pauling <aenertia@aenertia.net>

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
